<?php
	function rhe_allotment_menu() {	
		$items['rhe_allotment'] = array(
		  'title' => 'RHE Allotment',
		  'page callback' => 'drupal_get_form',
		  'page arguments' => array('rhe_allotment_form'),
		  'file' => 'rhe_allotment_page.inc',
		  'access arguments' => array('administer rhe allotment'),
		);

		/* $items['rhe_allotment/%'] = array(
		  'title' => 'RHE Allotment',
		  'page callback' => 'rhe_allotment_update',
		  'page arguments' => array(1),
		  'file' => 'rhe_allotment_update.inc',
		  'access arguments' => array('administer rhe allotment'),
		); */
		/* $items['rhe_allotment/%/%'] = array(
		  'title' => 'RHE Allotment',
		  'page callback' => 'rhe_allotment_update',
		  'page arguments' => array(1,2),
		  'file' => 'rhe_allotment_update.inc',
		  'access arguments' => array('administer rhe allotment'),
		); */
		
		return $items;
		
	}
		
		
function rhe_allotment_permission() {
	return array(
		'administer rhe allotment' => array(
		  'title' => t('Administer rhe allotment'),
		  'description' => t('Perform administer rhe allotment.'),
		),
		
	);
  
}		



function get_estatewise_vacancy($allotment_type, $district_code = 0) {
	$status_id = 1; // for "ready to allot" flat
	// $district_code = 17; // for Kolkata 
	$result = "";

	// array('Ground' => 'Ground', 'First' => 'First', 'Second' => 'Second', 'Third' => 'Third','Fourth'=>'Fourth','Fifth'=>'Fifth','Sixth'=>'Sixth','Seventh'=>'Seventh','Eighth'=>'Eighth','Ninth'=>'Ninth','Tenth'=>'Tenth')

	if(!empty($allotment_type)) {
		$result = db_query("SELECT t2.estate_id, t2.estate_name,
		count(case when t1.floor = 'Ground' then t1.flat_id end) as floor_0,
		count(case when t1.floor = 'First' then t1.flat_id end) as floor_1,
		count(case when t1.floor = 'Second' then t1.flat_id end) as floor_2,
		count(case when t1.floor = 'Third' then t1.flat_id end) as floor_3,
		count(case when t1.floor = 'Fourth' then t1.flat_id end) as floor_4,
		count(case when t1.floor = 'Fifth' then t1.flat_id end) as floor_5,
		count(case when t1.floor = 'Sixth' then t1.flat_id end) as floor_6,
		count(case when t1.floor = 'Seventh' then t1.flat_id end) as floor_7,
		count(case when t1.floor = 'Eighth' then t1.flat_id end) as floor_8,
		count(case when t1.floor = 'Top' then t1.flat_id end) as floor_top

		FROM housing_flat AS t1
		INNER JOIN housing_estate AS t2 ON t1.estate_id = t2.estate_id
		INNER JOIN housing_district AS t3 ON t2.district_code = t3.district_code
		WHERE t1.flat_type_id = " . $allotment_type . "
		AND t1.flat_status_id = " . $status_id . "
		AND t3.district_code = " . $district_code . "
		GROUP BY t2.estate_id, t2.estate_name
		ORDER BY t2.estate_name");
	}
	// print_r($result);die;
	return $result;
}
function get_no_of_applicant_vs($allotment_type, $occupation_estate) {
	$no_of_applicant = 0;
	// echo $allotment_type;die; 
	
	if(!empty($allotment_type) && !empty($occupation_estate)) {
		$result = db_query("SELECT count(*) as total_applicant FROM housing_online_application as t1
					INNER JOIN housing_vs_application as t2 ON t1.online_application_id = t2.online_application_id
					WHERE t1.status = 'housingapprover_approved_1'
					AND t2.flat_type_id = " . $allotment_type . " AND t2.occupation_estate = " . $occupation_estate);
					
		$record = $result->fetchObject();
		$no_of_applicant = $record -> total_applicant;
		//housing_sup_approved_1 to housingapprover_approved_1 by debaleena 04-09-2024
	}	
	
	return $no_of_applicant;	
}

function get_no_of_applicant_cs($allotment_type, $occupation_estate) {
	$no_of_applicant = 0;
	
	if(!empty($allotment_type) && !empty($occupation_estate)) {
		$result = db_query("SELECT count(*) as total_applicant FROM housing_online_application as t1
					INNER JOIN housing_cs_application as t2 ON t1.online_application_id = t2.online_application_id
					WHERE t1.status = 'housingapprover_approved_1'
				AND t2.flat_type_id = " . $allotment_type . " AND t2.occupation_estate = " . $occupation_estate);
				////AND t2.flat_type_id = " . $allotment_type);
		$record = $result->fetchObject();
		$no_of_applicant = $record -> total_applicant;
	}	
	//housing_sup_approved_1 to housingapprover_approved_1 by debaleena 04-09-2024
	return $no_of_applicant;	
}
function get_no_of_applicant_new($allotment_type = '') {
	$no_of_applicant = 0;
	
	if(!empty($allotment_type)) {
		$result = db_query("SELECT count(*) as total_applicant FROM housing_online_application as t1
					INNER JOIN housing_new_allotment_application as t2 ON t1.online_application_id = t2.online_application_id
					WHERE t1.status = 'housingapprover_approved_1'
					AND t2.flat_type_id = " . $allotment_type);

		$record = $result->fetchObject();
		$no_of_applicant = $record -> total_applicant;
	}	
	//housing_sup_approved_1 to housingapprover_approved_1 by debaleena 04-09-2024
	return $no_of_applicant;	
}


//////////////////added by debaleena 24.07.2024//////////////////////

function get_applicant_total_count($allotment_type = ''){

	$no_of_applicant = 0;
	
	if(!empty($allotment_type)) {
		//housing_sup_approved_1 to housingapprover_approved_1 by debaleena 04-09-2024
		$result_new = db_query("SELECT count(*) as total_applicant FROM housing_online_application as t1
					INNER JOIN housing_new_allotment_application as t2 ON t1.online_application_id = t2.online_application_id
					WHERE t1.status = 'housingapprover_approved_1'
					AND t2.flat_type_id = " . $allotment_type);

		$record_new = $result_new->fetchObject();
		$no_of_applicant_new = $record_new -> total_applicant;
		

		$result_cs = db_query("SELECT count(*) as total_applicant FROM housing_online_application as t1
					INNER JOIN housing_cs_application as t2 ON t1.online_application_id = t2.online_application_id
					WHERE t1.status = 'housingapprover_approved_1'
				AND t2.flat_type_id = " . $allotment_type);
				////AND t2.flat_type_id = " . $allotment_type);
		$record_cs = $result_cs->fetchObject();
		$no_of_applicant_cs = $record_cs -> total_applicant;

		$result_vs = db_query("SELECT count(*) as total_applicant FROM housing_online_application as t1
					INNER JOIN housing_vs_application as t2 ON t1.online_application_id = t2.online_application_id
					WHERE t1.status = 'housingapprover_approved_1'
					AND t2.flat_type_id = " . $allotment_type);
					
		$record_vs = $result_vs->fetchObject();
		$no_of_applicant_vs = $record_vs -> total_applicant;
		
	}	

	if($no_of_applicant_new > 0 || $no_of_applicant_cs > 0 || $no_of_applicant_vs){
	
		return '1';
	}else{

		return '0';
	}
	
	//return $no_of_applicant;	
}

////////////////////////end///////////////////////

function get_vacancy_details($allotment_type, $estate_id, $application_type, $district_code = 0) {
	$vacancy_details = array(); $condition = "";
	// $floor['vs'] = "('F','S')";
	// $floor['cs'] = "('G', 'T')";
	$floor['vs'] = "('First','Second','Third','Fourth','Fifth','Sixth','Seventh','Eighth')";
	$floor['cs'] = "('Ground', 'Top')";

	if(isset($estate_id) && !empty($estate_id)) {
		$condition .= " AND t2.estate_id = " . $estate_id;
	}

	$result = db_query("SELECT t1.* FROM housing_flat AS t1
	INNER JOIN housing_estate AS t2 ON t1.estate_id = t2.estate_id
	INNER JOIN housing_district AS t3 ON t2.district_code = t3.district_code
	WHERE t1.flat_type_id = " . $allotment_type . "
	AND t1.flat_status_id = 1
	AND t3.district_code = ".$district_code."
	AND t1.floor IN " . $floor[$application_type] . $condition);

	if($result -> rowCount() > 0) {
		foreach($result as $record) {
			$vacancy_details[] = array(
				'estate_id' => $record -> estate_id,
				'flat_id' => $record -> flat_id,
				'flat_type_id' => $record -> flat_type_id,
			);
		}
	}
	return $vacancy_details;
}
function get_total_vacancy_new($allotment_type, $district_code = 0) {
	$result = db_query("SELECT count(*) as total_vacancy FROM housing_flat AS t1
	INNER JOIN housing_estate AS t2 ON t1.estate_id = t2.estate_id
	INNER JOIN housing_district AS t3 ON t2.district_code = t3.district_code
	WHERE t1.flat_type_id = " . $allotment_type . "
	AND t1.flat_status_id = 1
	AND t3.district_code =".$district_code." ");

	$record = $result -> fetchObject();
	return $record -> total_vacancy;
}

		