<?php
	global $entities;
	
	$entities = array();

	function common_application_init() {
		global $base_url;
		global $base_root;
		global $base_path;
		
		//echo $base_path.'<br>'.$base_root.'<br>'.$base_url.'<br>'.current_path();
		
		$path = current_path();
    	if(!drupal_valid_path($path))
        	drupal_goto($base_root.$base_path);
		
		//comment off these 3 lines for live
		global $custom_url;		
			
		$arr = explode('/',$base_url);
		
		for ($i=3; $i < count($arr); $i++) { 
            $custom_url .= '/'.$arr[$i];
        }
		
		drupal_add_library('system','ui.datepicker');
		
		//drupal_add_js('js/common_application.js');
		/*drupal_add_js('
						function isNumberKey(e) {
							var unicode = e.charCode ? e.charCode : e.keyCode
							if (unicode!=8){
								if (unicode<48 || unicode>57)
									return false
							}
						}   
					','inline'
		);*/
			
		global $user;
		
		
		$query = db_select('housing_applicant', 'ha');
		$query->fields('ha', array('applicant_name'));
		
		$query->condition('ha.uid', $user->uid, '=');
		
		$result = $query->execute();
		$row_count = $result->rowCount();
		if($row_count > 0) {
			$data = $result->fetchObject();
			global $user_info;
			$user_info = $data->applicant_name;
		}
	}	
	
 	function common_application_menu() {
		$items['application-status/%'] = array(
			'title' => 'Application Status',	
			'page callback' => 'application_status_page',
			'page arguments' => array(1),
			'access arguments' => array('access content'),
		);
		return $items;
  	}
    
	function application_status_page($status = '') {
		if(!empty($status))
		$msg = 'Your status: '.$status;
		return $msg;
	}
  
	function application_form($form, &$form_state) {
		// echo'1st';die;
		// echo "<pre>";print_r($form_state['values']);die;
		global $user;
				
		$query = db_select('housing_applicant', 'ha');
		$query->fields('ha');
		$query->condition('ha.uid', $user->uid, '=');
		$result = $query->execute();
		$row_count = $result->rowCount();
		if($row_count > 0) {
			$applicant_info = $result->fetchObject();
		}
		
		
		$district = isset($form_state['values']['district']) && !empty($form_state['values']['district']) ? $form_state['values']['district'] : '';
		
		$designation = isset($form_state['values']['designation']) && !empty($form_state['values']['designation']) ? $form_state['values']['designation'] : '';
		$dob = isset($form_state['values']['dob']) && !empty($form_state['values']['dob']) ? $form_state['values']['dob'] : '';
		
		//$chk_permanent_address = isset($form_state['values']['chk_permanent_address'][1]) && !empty($form_state['values']['chk_permanent_address'][1]) ? $form_state['values']['chk_permanent_address'][1] : $applicant_info->permanent_present_same;
		//turned off18-11-2024
		// $chk_permanent_address = isset($form_state['values']['chk_permanent_address']) ? $form_state['values']['chk_permanent_address'] : $applicant_info->permanent_present_same;
	
		
		$form['form_begin'] = array(
			'#type' => 'markup',
			'#markup' => '<div class="online_application">',
			'#weight' => -2
		);
		
		// personal information
		$form['prrsonal_info'] = array(
			'#type' => 'fieldset',
			'#title' => t('Personal Information(According to Service Book)'),
			'#collapsible' => FALSE, // Added
			'#collapsed' => FALSE,  // Added
		);
		
		
		/*$form['prrsonal_info']['online_app_id'] = array(
			'#type' => 'hidden',
			'#default_value' => get_online_appid($user->uid),
			//'#validated' => TRUE,
		);*/
		/*$form['prrsonal_info']['online_app_id'] = array(
			'#type' => 'textfield',
			'#default_value' => 0,
			//'#validated' => TRUE,
		);*/


		$form['prrsonal_info']['applicant_name'] = array(
			'#title' => t('Applicant\'s Name'),
			'#type' => 'textfield',
			// '#prefix' => '<div class="two">',
			
			'#prefix' => '<div class="row"><div class="col-md-6"><div class="form-floating">',
			'#suffix' => '</div></div>',

			'#element_validate' => array('element_validate_alphabatic_fullstop'), 
			'#required' => TRUE,
			'#attributes' => array('oninput'=>"this.value=this.value.toUpperCase()", 'class'=>array('form-control')), 
		);
		
		$form['prrsonal_info']['applicant_father_name'] = array(
			'#title' => t('Father\'s / Husband\'s Name'),
			'#type' => 'textfield',
			'#default_value' => '',
			'#prefix' => '<div class="col-md-6"><div class="form-floating">',
			'#suffix' => '</div></div></div>',

			'#element_validate' => array('element_validate_alphabatic_fullstop'), 
			'#required' => TRUE,
			'#attributes' => array('oninput'=>"this.value=this.value.toUpperCase()", 'class'=>array('form-control')),
		);


		//Permanent Address
		$form['prrsonal_info']['permanent_address'] = array(
			'#type' => 'fieldset',
			'#title' => t('Permanent Address'),
			'#collapsible' => FALSE, // Added
			'#collapsed' => FALSE,  // Added
		);

		$form['prrsonal_info']['permanent_address']['permanent_street'] = array(
			'#title' => t('Address'),
			'#type' => 'textfield',
			'#required' => TRUE,
			'#prefix' => '<div class="row"><div class="col-md-6"><div class="form-floating">',
			'#suffix' => '</div></div>',
			'#element_validate' => array('element_validate_streetaddress'), 
			'#attributes' => array('oninput'=>"this.value=this.value.toUpperCase()", 'class'=>array('form-control')),
			
		);
		$form['prrsonal_info']['permanent_address']['permanent_city_town_village'] = array(
			'#title' => t('City / Town / Village'),
			'#type' => 'textfield',
			'#required' => TRUE,
			'#prefix' => '<div class="col-md-6"><div class="form-floating">',
			'#suffix' => '</div></div></div>',
			'#element_validate' => array('element_validate_alphabatic_text'), 
			'#attributes' => array('oninput'=>"this.value=this.value.toUpperCase()", 'class'=>array('form-control')),
			
		);
		$form['prrsonal_info']['permanent_address']['permanent_post_office'] = array(
			'#title' => t('Post Office'),
			'#type' => 'textfield',
			'#required' => TRUE,
			'#prefix' => '<div class="row"><div class="col-md-4"><div class="form-floating">',
			'#suffix' => '</div></div>',
			'#element_validate' => array('element_validate_alphabatic_text'), 
			'#attributes' => array('oninput'=>"this.value=this.value.toUpperCase()", 'class'=>array('form-control')),
			
		);
		$form['prrsonal_info']['permanent_address']['permanent_district'] = array(
			'#title' => t('District'),
			'#type' => 'select',
			'#options' => district_list(),
			'#required' => TRUE,
			'#prefix' => '<div class="col-md-4"><div class="form-floating">',
			'#suffix' => '</div></div>',
			'#attributes' => array('class'=>array('form-select'))
		);
		$form['prrsonal_info']['permanent_address']['permanent_pincode'] = array(
			'#title' => t('Pincode'),
			'#type' => 'textfield',
			'#maxlength' => 6,
			'#required' => TRUE,
			'#element_validate' => array('element_validate_numeric_positive'), 
			'#prefix' => '<div class="col-md-4"><div class="form-floating">',
			'#suffix' => '</div></div></div>',
			'#attributes' => array('class' => array('numeric_positive'), 'class'=>array('form-control')),
		);
		//end

		// $form['prrsonal_info']['chk_permanent_address'] = array(
		// 	'#type' => 'checkbox',
		// 	'#title' => 'Check if Your Present Address is same as Your Permanent Address.',
		// 	'#default_value' => $applicant_info->permanent_present_same,
		// 	'#disabled' =>TRUE,
		// 	'#prefix' => '<div class="col-md-12"><div class="form-check">',
		// 	'#suffix'	=> '</div></div>',
		// 	'#attributes' => array('class'=>array('form-check-input')),     
		// 	'#ajax' => array(
		// 			   'event' => 'change',
		// 			   'callback' => '_reload_present_address',
		// 			   'wrapper' => 'replace_present_address',
		// 			   'effect' => 'fade',
		// 			   'progress' => array(
		// 				  'type' => '',
		// 				  'message' => '',
		// 				), 
		// 	 ),
	    // );

		//if($chk_permanent_address != 1) {
		//Present Address
		$form['prrsonal_info']['present_address'] = array(
			'#type' => 'fieldset',
			'#title' => t('Present Address'),
			'#collapsible' => FALSE, // Added
			'#collapsed' => FALSE,  // Added
			'#prefix' => '<div id="reload_present_address">',
			'#suffix' => '</div>',
			
		);
		$form['prrsonal_info']['present_address']['present_street'] = array(
			'#title' => t('Address'),
			'#type' => 'textfield',
			'#required' => TRUE,
			'#prefix' => '<div class="row"><div class="col-md-6" id="reload_present_street"><div class="form-floating">',
			'#suffix' => '</div></div>',
			'#element_validate' => array('element_validate_streetaddress'), 
			'#attributes' => array('oninput'=>"this.value=this.value.toUpperCase()", 'class'=>array('form-control')), //'id' => 'present_street',
			
		);
		$form['prrsonal_info']['present_address']['present_city_town_village'] = array(
			'#title' => t('City / Town / Village'),
			'#type' => 'textfield',
			'#required' => TRUE,
			'#prefix' => '<div class="col-md-6" id="reload_present_city_town_village"><div class="form-floating">',
			'#suffix' => '</div></div></div>',
			'#element_validate' => array('element_validate_alphabatic_text'), 
			'#attributes' => array('oninput'=>"this.value=this.value.toUpperCase()", 'class'=>array('form-control')), //'id' => 'present_city_town_village', 
			
		);
		$form['prrsonal_info']['present_address']['present_post_office'] = array(
			'#title' => t('Post Office'),
			'#type' => 'textfield',
			'#required' => TRUE,
			'#prefix' => '<div class="row"><div class="col-md-4" id="reload_present_post_office"><div class="form-floating">',
			'#suffix' => '</div></div>',
			'#element_validate' => array('element_validate_alphabatic_text'), 
			'#attributes' => array('oninput'=>"this.value=this.value.toUpperCase()", 'class'=>array('form-control')), //'id' => 'present_post_office', 
			
		);
		$form['prrsonal_info']['present_address']['present_district'] = array(
			'#title' => t('District'),
			'#type' => 'select',
			'#options' => district_list(),
			'#required' => TRUE,
			'#prefix' => '<div class="col-md-4" id="reload_present_district"><div class="form-floating">',
			'#suffix' => '</div></div>',
			//'#attributes' => array('id' => 'present_district'),
			// '#select2' => array(
			// 	'width' => '500',
			// 	//'placeholder' => '- Select -',
			// 	'allowClear' => TRUE
			// ),
			'#attributes' => array('class'=>array('form-select'))
		);
		$form['prrsonal_info']['present_address']['present_pincode'] = array(
			'#title' => t('Pincode'),
			'#type' => 'textfield',
			'#maxlength' => 6,
			'#required' => TRUE,
			'#element_validate' => array('element_validate_numeric_positive'), 
			'#prefix' => '<div class="col-md-4" id="reload_present_pincode"><div class="form-floating">',
			'#suffix' => '</div></div></div>',
			'#attributes' => array('class' => array('numeric_positive'), 'class'=>array('form-control')), //'id' => 'present_pincode', 
			
		);
	/*} else {
		$form['prrsonal_info']['present_address'] = array(
			'#prefix' => '<div id="reload_present_address">',
			'#suffix' => '</div>',
		);
		/*$form['prrsonal_info']['present_address']['present_street'] = array(
			'#prefix' => '<div id="reload_present_street">',
			'#suffix' => '</div>',
		);
		$form['prrsonal_info']['present_address']['present_city_town_village'] = array(
			'#prefix' => '<div id="reload_present_city_town_village">',
			'#suffix' => '</div>',
		);
		$form['prrsonal_info']['present_address']['present_post_office'] = array(
			'#prefix' => '<div id="reload_present_post_office">',
			'#suffix' => '</div>',
		);
		$form['prrsonal_info']['present_address']['present_district'] = array(
			'#prefix' => '<div id="reload_present_district">',
			'#suffix' => '</div>',
		);
		$form['prrsonal_info']['present_address']['present_pincode'] = array( 
			'#prefix' => '<div id="reload_present_pincode">',
			'#suffix' => '</div>',
		);
	}*/
	//end

	$form['prrsonal_info']['mobile'] = array(
		'#title' => t('Mobile no'),
		'#type' => 'textfield',
		'#default_value' => '',
		'#maxlength' => 10,
		'#required' => TRUE,
		'#prefix' => '<div class="row"><div class="col-md-4"><div class="form-floating">',
		'#suffix' => '</div></div>',
		'#element_validate' => array('element_validate_mobile', 'mobile_no_validate'),
		'#attributes' => array('id' => 'mobile_no', 'class'=>array('form-control')),
		
	);
	
	$form['prrsonal_info']['email'] = array(
		'#title' => t('Email ID'),
		'#type' => 'textfield',
		'#prefix' => '<div class="col-md-4"><div class="form-floating">',
		'#suffix' => '</div></div>',
		'#element_validate' => array('element_validate_email', 'email_id_validate'),
		'#default_value' => '',
		'#required' => TRUE,
		'#attributes' => array('class'=>array('form-control')),
		
	);
	
	if (empty($user->mail)) {
		$form['prrsonal_info']['email']['#attributes'] = array('oninput'=>"this.value=this.value.toLowerCase()",'class'=>array('form-control'));
	}
	
	$form['prrsonal_info']['dob'] = array(
		'#title' => t('Date of Birth(According to Service Book)'),
		'#type' => 'textfield',
		'#attributes' => array('id' => 'edit-dob', 'class'=>array('form-control')),
		'#required' => TRUE,
		'#disabled'=>TRUE,
		'#prefix' => '<div class="col-md-4"><div class="form-floating">',
		'#suffix' => '</div></div></div>',
		'#element_validate' => array('element_validate_date', 'element_validate_age'),
	);
	
	$form['prrsonal_info']['gender'] = array(
		'#title' => t('Gender'),
		'#type' => 'radios',
		'#options' => array('M' => 'Male', 'F' => 'Female'),
		'#attributes' => array('class' => array('form-check-input')),
		'#default_value' => '',
		// '#default_value' => 'M',
		'#prefix' => '<div class="col-md-4"><div class="">',
		'#suffix' => '</div></div>',
		'#required' => TRUE,
		
	);
		
	// applicant's official information
	$form['official_info'] = array(
		'#type' => 'fieldset',
		'#title' => t('Applicant\'s Official Information'),
		'#collapsible' => FALSE, // Added
		'#collapsed' => FALSE,  // Added
	);
	$form['official_info']['hrms_id'] = array(
		'#title' => t('Employee HRMS ID'),
		'#type' => 'textfield',
		'#required' => TRUE,
		'#maxlength' => 10,
		'#prefix' => '<div class="row"><div class="col-md-4"><div class="form-floating">',
		'#suffix' => '</div></div>',
		'#element_validate' => array('element_validate_hrms_id', 'hrms_id_validate'),
		'#attributes' => array('class' => array('numeric_positive form-control')),
	);
	$form['official_info']['app_designation'] = array(
		'#title' => t('Designation'),
		'#type' => 'textfield',
		'#required' => TRUE,
		'#prefix' => '<div class="col-md-4"><div class="form-floating">',
		'#suffix' => '</div></div>',
		'#element_validate' => array('element_validate_textarea'),
		'#attributes' => array('oninput'=>"this.value=this.value.toUpperCase()",'class'=>array('form-control')),
		//'#attributes' => array('id' => 'edit-app-designation', 'oncopy' => "return false", 'onpaste' => "return false"),
		
	);
	$form['official_info']['pay_band'] = array(
		'#title' => t('Basic Pay Range'),
		'#type' => 'select',
		'#options' => pay_band_list(),
		'#required' => TRUE,
		'#prefix' => '<div class="col-md-4"><div class="form-floating">',
		'#suffix' => '</div></div></div>',
		'#validated' => TRUE,
		'#attributes' => array('class'=>array('form-select'))
		
	);
	$form['official_info']['pay_in'] = array(
		 '#title' => t('Basic Pay'),
		'#type' => 'textfield',
		 '#required' => TRUE,
		 '#element_validate' => array('element_validate_numeric_positive'), 
		 '#prefix' => '<div class="row"><div class="col-md-4"><div class="form-floating">',
		 '#suffix' => '</div></div>',
		 '#attributes' => array('class' => array('numeric_positive form-control')),
	);
	
	// $form['official_info']['grade_pay'] = array(
	// 	'#title' => t('Grade Pay'),
	// 	'#type' => 'textfield',
	// 	'#required' => TRUE,
	// 	'#element_validate' => array('element_validate_numeric_positive'), 
	// 	'#prefix' => '<div class="four">',
	// 	'#suffix' => '</div>',
	// 	'#attributes' => array('class' => array('numeric_positive')),
	// );
	
	/*$form['official_info']['gpf_no'] = array(
		'#title' => t('GPF No.'),
		'#type' => 'textfield',
		'#required' => TRUE,
		'#element_validate' => array('gpf_no_validate'), 
		'#prefix' => '<div class="three">',
		'#suffix' => '</div>',
		'#attributes' => array('oninput'=>"this.value=this.value.toUpperCase()"),
	);*/
	
	$form['official_info']['app_posting_place'] = array(
		'#title' => t('Place of Posting'),
		'#type' => 'textfield',
		'#required' => TRUE,
		'#prefix' => '<div class="col-md-4"><div class="form-floating">',
		'#suffix' => '</div></div>',
		//'#element_validate' => array('element_validate_alphabatic_text'),
		'#attributes' => array('oninput'=>"this.value=this.value.toUpperCase()", 'class' => array('form-control')), 
		
	); 
	$form['official_info']['app_headquarter'] = array(
		'#title' => t('Headquarter'),
		'#type' => 'textfield',
		'#required' => TRUE,
		'#prefix' => '<div class="col-md-4"><div class="form-floating">',
		'#suffix' => '</div></div></div>',
		'#element_validate' => array('element_validate_alphabatic_text'),
		'#attributes' => array('oninput'=>"this.value=this.value.toUpperCase()", 'class' => array('form-control')), 
		
	);
	$form['official_info']['doj'] = array(
		'#title' => t('Date of Joining'),
		'#type' => 'textfield',
		//'#attributes' => array('readonly' => 'readonly', 'id' => 'edit-doj'),
		'#attributes' => array('id' => 'edit-doj', 'class' => array('numeric_positive form-control')),
		'#default_value' => '',
		'#required' => TRUE,
		'#prefix' => '<div class="row"><div class="col-md-6"><div class="form-floating">',
		'#suffix' => '</div></div>',
		'#element_validate' => array('element_validate_date', 'element_validate_joining_age'),
		
	);
	
	$form['official_info']['dor'] = array(
		'#title' => t('Date of Retirement(According to Service Book)'),
		'#type' => 'textfield',
		//'#value' => $date2,
		//'#attributes' => array('readonly' => 'readonly', 'id' => 'edit-dor'),
		'#attributes' => array('id' => 'edit-dor', 'class' => array('numeric_positive form-control')),
		'#default_value' => '',
		'#required' => TRUE,
		//#prefix' => '<div class="four" id="replace_dor">',
		'#prefix' => '<div class="col-md-6"><div class="form-floating">',
		'#suffix' => '</div></div></div>',
		'#element_validate' => array('element_validate_date'),
		
	);


	// applicant's office address
	$form['office_add'] = array(
		'#type' => 'fieldset',
		'#title' => t('Name and Address of the Office'),
		'#collapsible' => FALSE, // Added
		'#collapsed' => FALSE,  // Added
	);

	$form['office_add']['office_name'] = array(
		'#title' => t('Name of the Office'),
		'#type' => 'textfield',
		'#required' => TRUE,
		'#prefix' => '<div class="row"><div class="col-md-4"><div class="form-floating">',
		'#suffix' => '</div></div>',
		'#element_validate' => array('element_validate_textarea'), 
		'#attributes' => array('oninput'=>"this.value=this.value.toUpperCase()", 'class' => array('numeric_positive form-control')),
		
	);
	
	$form['office_add']['office_street'] = array(
		'#title' => t('Address'),
		'#type' => 'textfield',
		'#required' => TRUE,
		'#prefix' => '<div class="col-md-4"><div class="form-floating">',
		'#suffix' => '</div></div>',
		//'#element_validate' => array('element_validate_streetaddress'), 
		'#attributes' => array('oninput'=>"this.value=this.value.toUpperCase()"),
		
	);
	$form['office_add']['office_city'] = array(
		'#title' => t('City / Town / Village'),
		'#type' => 'textfield',
		'#required' => TRUE,
		'#prefix' => '<div class="col-md-4"><div class="form-floating">',
		'#suffix' => '</div></div></div>',
		'#element_validate' => array('element_validate_alphabatic_text'), 
		'#attributes' => array('oninput'=>"this.value=this.value.toUpperCase()", 'class' => array('form-control')),
		
	);
	$form['office_add']['office_post_office'] = array(
		'#title' => t('Post Office'),
		'#type' => 'textfield',
		'#required' => TRUE,
		'#prefix' => '<div class="row"><div class="col-md-3"><div class="form-floating">',
		'#suffix' => '</div></div>',
		'#element_validate' => array('element_validate_alphabatic_text'), 
		'#attributes' => array('oninput'=>"this.value=this.value.toUpperCase()", 'class' => array('form-control')),
		
	);
	$form['office_add']['office_district'] = array(
		'#title' => t('District'),
		'#type' => 'select',
		'#options' => district_list(),
		'#required' => TRUE,
		'#prefix' => '<div class="col-md-3"><div class="form-floating">',
		'#suffix' => '</div></div>',
		'#attributes' => array('class' => array('form-select'))
	);
	$form['office_add']['office_pincode'] = array(
		'#title' => t('Pincode'),
		'#type' => 'textfield',
		'#maxlength' => 6,
		'#required' => TRUE,
		'#element_validate' => array('element_validate_numeric_positive'), 
		'#prefix' => '<div class="col-md-3"><div class="form-floating">',
		'#suffix' => '</div></div>',
		'#attributes' => array('class' => array('numeric_positive form-control')),
		
	);
	$form['office_add']['office_phone_no'] = array(
		'#title' => t('Phone No.(With STD Code)'),
		'#type' => 'textfield',
		'#maxlength' => 15,
		'#required' => TRUE,
		'#element_validate' => array('element_validate_telephoneno'), 
		'#prefix' => '<div class="col-md-3"><div class="form-floating">',
		'#suffix' => '</div></div></div>',
		'#attributes' => array('class' => array('numeric_positive form-select')),
		
	);

	// ddo details
	$form['ddo'] = array(
		'#type' => 'fieldset',
		'#title' => t('DDO with full address'),
		'#collapsible' => FALSE, // Added
		'#collapsed' => FALSE,  // Added
	);

	$form['ddo']['district'] = array(
		'#title' => t('DDO District'),
		'#type' => 'select',
		'#options' => district_list(),
		'#ajax' => array(
				   'event' => 'change',
				   'callback' => '_reload_ddo_designation',
					  'wrapper' => 'replace_designation',
				   'effect' => 'fade',
				   'progress' => array(
					  'type' => '',
					  'message' => '',
					), 
		 ),
		'#required' => TRUE,
		'#validated' => TRUE,
		'#prefix' => '<div class="row"><div class="col-md-6"><div class="form-floating">',
		'#suffix' => '</div></div>',
	);
	
	
	$form['ddo']['designation'] = array(
		'#title' => t('DDO Designation'),
		'#type' => 'select',
		//'#options' => array('- Select -'),
		'#options' => ddo_desig_list($district),
		'#ajax' => array(
				   'event' => 'change',
				   'callback' => '_reload_ddo_address',
				   'wrapper' => 'replace_ddo_address',
				   'effect' => 'fade',
				   'progress' => array(
					  'type' => '',
					  'message' => '',
					 ),
		 ),
		'#default_value' => $designation,
		'#required' => TRUE,
		'#validated' => TRUE,
		'#prefix' => '<div id="replace_designation" class="col-md-6"><div class="form-floating">',
		'#suffix' => '</div></div>',
	);
	
	$form['ddo']['address'] = array(
		'#title' => t('DDO Address'),
		'#type' => 'textarea',
		'#prefix' => '<div id="replace_ddo_address" class="col-md-6"><div class="form-floating">',
		'#suffix' => '</div></div>',
		'#attributes' => array('class' => array('form-control')) 
		//'#required' => TRUE,
		//'#validated' => TRUE,
	);

	$form['submit'] = array(
		'#prefix' =>'<div class="col-12 border-top pt-3">',
		'#suffix' => '</div><div class="mb-5 pb-3"></div>',
		'#value' => t('Apply'),
		'#type' => 'submit',
		'#weight' => 51,
		'#attributes' => array('onclick' => 'if(!confirm("Are you sure you want to submit the form? Once the form submitted the data can\'t be edited.")){return false;}', 'class'=>array('btn bg-primary btn-sm px-5 rounded-pill text-white fw-bolder')),
	);

	$form['form_end'] = array(
		'#type' => 'markup',
		'#markup' => '</div>',
	);
		


		
		return $form;
	}
	
	
  
	require_once('common_application_fetch_data.form.inc');
	require_once('common_application_add_data.form.inc');
	require_once('common_application_update_data.form.inc');
	require_once('common_application_validate.form.inc');
	
	
	
	/*function get_online_appid($uid) { 
		$online_app_id = 0;
		
		$data = db_query("select t1.online_application_id from {housing_online_application} as t1
							inner join {housing_applicant_official_detail} as t2
							on t1.applicant_official_detail_id = t2.applicant_official_detail_id
							where t2.uid = :uid", array(':uid' => $uid))->fetchAssoc();
	
	   $online_app_id = $data['online_application_id'];
	   return $online_app_id;
	}*/
	
//code needed if drupal_mail() used	
	/*function common_application_mail($key, &$message, $params) {
		switch($key) {

			case 'registration_approve':
				$message['subject'] = $params['subject']; 
				$message['body'][] = $params['message'];
				$message['headers'] += $params['headers'];
			break;
		}
		
	}*/

// get district code from HRMIS district code 26-06-2024

function getDistrictCodeByHRMS($hrms_district_id=''){
	if($hrms_district_id !=''){
		$query = "SELECT district_code FROM housing_district where hrms_district_id=".$hrms_district_id;
		$result = db_query($query)->fetchAssoc();
		// print_r($result);die;
		return $result['district_code'];
	}else{
		return '';
	}
}


// Done by Subham 22-11-2024
function get_status_id($status = ''){
	// $status = decrypt_url($status);
	
	$query = db_select('housing_allotment_status_master', 'hasm');
	$query->addField('hasm', 'status_id');
	$query->condition('hasm.short_code',$status,'=');
	$result = $query->execute();  
	$data = $result->fetchAssoc();
	
	return $data['status_id'];
}