<?php
// Done by Subham dt.28-05-2025
function user_tagging_menu() {
  $items = array();

  $items['user-tagging'] = array(
    'title' => 'Form For User Tagging',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('user_tagging_form'),
    'file' => 'user_tagging_form.inc',
    'access arguments' => array('administer User Tagging'),
	);

  $items['flat-wise-user-info'] = array(
    'title' => 'Form For User Tagging',
    'page callback' => 'flat_wise_user_info',
    'page arguments' => array(1,2),
    'file' => 'flat_wise_user_info.inc',
    'access arguments' => array('access content'),
	);


  return $items;
}

function user_tagging_permission() {
  return array(
    'administer User Tagging' => array(
      'title' => t('administer User Tagging'),
      'description' => t('perform administer for User Tagging.')
    )
  );	
}